- src/lib.rs
- src/middleware.rs
This cleans up the chain by which we call perform_async through the several means. Fixes a bug where worker opts were not propagated to the `perform_{in,async}` call. Kind of cool that demo.rs required no changes. Compiles and builds just fine.
I made `max_retries(&self)` a function on the Worker trait because `Box<dyn Worker>` is not `Sized`, therefore I can't call the `T::opts()` method, which would have been really nice. But, that's ok. I might need to re-think the worker opts pattern. Ideally we could rely on EnqueueOpts, but there's diverging perform functions where EnqueueOpts requires a class string, but WorkerOpts doesn't because it knows it ahead of time through the trait definition.
> Refactor perform_async opts

- README.md
- examples/demo.rs
- src/middleware.rs
- src/processor.rs
This removes unnecessary clone calls and makes `Job` a reference through the middleware interface. It might make sense to have `args: JsonValue` be a reference as well. The reason I'm not sure yet is that clone is required to call `serde_json::from_value` but not all jobs take arguments.
> Quick optimization pass

- Cargo.lock
- Cargo.toml
- README.md
- examples/demo.rs
- src/lib.rs
- src/middleware.rs
- src/processor.rs
This is a pretty major change to the lib, but since nobody is likely using it, I think we're ok.
I was hoping to make this lib use generic arguments at the start but couldn't find a way to make it work. The biggest thing I ran into was that I can't create a `Box<dyn Worker<T>>` without specifying `T` which made it impossible to build a data structure that could hold any variety of `Worker` and `T`.  However, through several interesting blog posts and stack overflow comments I realized I could hide the `T` by wrapping the invocation of the worker with a closure. In other words, because the input and output are the same for any `Box<dyn Worker<T>>`, the `T` could be encapsulated inside of a closure. To make things easier I created a `WorkerRef` type that holds the `Fn` trait impl and some …
> WIP: Rewrite Worker to be generic over Args

- Cargo.lock
- Cargo.toml
- README.md
- examples/demo.rs
- examples/namespaced_demo.rs
- src/lib.rs
- src/middleware.rs
- src/periodic.rs
- src/processor.rs
- src/redis.rs
- src/scheduled.rs
- tests/process_async_test.rs
- tests/process_cron_job_test.rs
- tests/process_scheduled_job_test.rs
Impl https://github.com/film42/sidekiq-rs/issues/7
This adds a shim around the redis connection to support namespaces similar to the https://github.com/resque/redis-namespace gem. This allows cooperation with ruby apps that depend on this feature.
There may be a slight uptick in allocations because I can't be as clever about passing by reference since we're going to mutate all keys for each redis call but that's something we may be able to optimize later.
The test suite is passing once again and I added an example showing how to activate the namespace mode.
Going to let this sit for a day and come back to review.
@justmark Would you mind trying to run your project against this PR?
To use namespace:
```rust
// Redis
let manager = RedisConnectionManager::new("redis://127.0.0.1/")?;
let …
```
> Support redis namespaces

- Cargo.toml
- src/lib.rs
- src/redis.rs
Pretty simple change but an important one. LIFO vs FIFO queue.
> Fix bug: We should use lpush not rpush

- src/lib.rs
- src/redis.rs
This will make queues show up and have their counts visible in sidekiq-web.
The server side is a much larger piece that requires a heartbeat and some process metrics. Still figuring out how to make that work in a clean way. This change is probably more important at the moment.
> Add queue to "queues" at enqueue time for stats

- Cargo.lock
- Cargo.toml
We can close (or take a few good ideas from #25 ). Looks like upgrading redis will fix the problem of infinite looping on error without recovery.
> Add a dep upgrade for latest redis with working retry

- src/lib.rs
- src/periodic.rs
- src/redis.rs
- src/scheduled.rs
- tests/server_middleware_test.rs
~~When an IO error is detected, we should be safe to assume the connection is down and needs to be recreated. Without this, it's possible for a process to be stuck in a loop that never recovers even though redis has come back online.~~
Updating the description:
Feel free to read the log below even though the real fix is found in #26 . Some of these changes are good and you can see how clippy fixes make the code easier and maybe even faster.
> Refactor redis wrapper to use RedisError type instead of generic Box

- src/lib.rs
- src/middleware.rs
- src/periodic.rs
- src/processor.rs
- src/redis.rs
- src/scheduled.rs
- src/stats.rs
This removes the requirement for a mut pool (which did not make sense, and severely limited use through a web framework)
_NOTE_: FYI in general there are some more warnings (via lints), which indicates some of the types require `Serialize` and are not `Send`, but I left it as-is for now.
> remove mut requirement for RedisPool, + some lint fixes

- Cargo.lock
- Cargo.toml
- README.md
- examples/consumer-demo.rs
- examples/demo.rs
- examples/namespaced_demo.rs
- examples/producer-demo.rs
- examples/unique.rs
- src/lib.rs
- src/middleware.rs
- src/periodic.rs
- src/processor.rs
- src/scheduled.rs
- tests/process_async_test.rs
- tests/process_cron_job_test.rs
- tests/process_scheduled_job_test.rs
- tests/process_unique_job_test.rs
- tests/server_middleware_test.rs
This PR moves from `slog` to `tracing` across the board.
Benefits:
* Move to more "standardized" logging
* Inversion of control - publisher-subscriber model, no longer need to pass `logger` around
* All the power and flexibility of tracing and opentracing at hand (filtering, formatting, collection, shipping to OTEL, and more)
* Integrate into production deployments better: one tracing filter/level to rule them all (i.e. filter across libraries such as sqlx)
* Opens up the possibility of `spans` across jobs, components and advanced instrumentation
* Removal of a good amount of code and an _aging_ infrastructure (slog, `log`)
> move from slog to tracing

- src/lib.rs
This pull request enhances the redis_rs library by enabling the utilization of a specified Redis version. This is achieved by allowing additional commands to be executed before registration. For instance, one can use the 'flushall' command as an example of a pre-registration command.
For example, I want to run this logic before registering:
```
if let Some(pool) = &redis {
let mut conn = pool.get().await.unwrap();
sidekiq::redis_rs::cmd("FLUSHDB")
.query_async::<_, ()>(conn.unnamespaced_borrow_mut())
.await
.unwrap();
}
```
> expose base redis lib

- Cargo.toml
- src/stats.rs
Hi,
There is a dependency issue, which causes unresolvable Cargo conflicts on macOS caused by a transitive dependency of `simple-process-stats`:
* see https://github.com/heim-rs/darwin-libproc/pull/9 on the core dependency issue, and the fact that `darwin-libproc` is not maintained actively to fix it
* sidekiq-rs needs `robotty/simple-process-stats` which depends on `darwin-libproc`, which depends on
a too old `memchr` version which many libraries, one example: `sqlx` needs. because `libproc` is native and not pure rust, cargo cannot resolve it.
since `simple_process_stats` use by `sidekiq-rs` is minimal only for getting `RSS`, its better to replace it with something that has more velocity on updating dependencies but that is also lightweight and cross platform (I didn't find one yet).
in …
> making simple-process-stats optional

- Cargo.lock
- Cargo.toml
- src/lib.rs
By switching from heck to convert_case we auto-fix this issue. The test case shows what was previously _not_ working and how convert_case does work. I spent some time going through the heck library but convert_case seems very popular and "just works" out of the box.
Closes https://github.com/film42/sidekiq-rs/issues/30
> Switch case lib due to bug with ruby style X1Y1Class shapes

- Cargo.lock
- Cargo.toml
- src/processor.rs
We've implemented graceful shutdown using [cancellation tokens from the tokio runtime](https://tokio.rs/tokio/topics/shutdown).
It allows users of this crate to optionally get the cancellation token, and send the shutdown signal to sidekiq.
The implementation is such that no on-hand work will ever be cancelled. This however means that sending a SIGINT doesn't mean immediate shutdown, as currently active jobs first need to finish. As soon as the cancellation token is cancelled, no new work will be taken on by the workers.
A minimal new example for using cancellation tokens is as follows:
```rust
// Sidekiq server
let mut p = Processor::new(
redis,
vec!["default".to_string()],
);
p.register(DemoWorker::new());
// Retrieve the cancellation token and store it
let cancellation_token = …
```
> Implement graceful shutdown using tokio cancellation tokens

- src/middleware.rs
Problem
--------
The `retry_count < max_retries` check is performed after `retry_count` is incremented. This means we need to use `<=` (or equivalently `>` with the conditional blocks reversed) to check if the max retries was exceeded. Otherwise, we will have an off-by-one error in the check.
For example, if we have `max_retries = 1`, `retry_count` will be incremented to equal `1` before the check, the check will fail because `retry_count(1) == max_retries(1)` and not `<`, and therefore the job will not retry.
Solution
--------
Flip the conditional blocks and use `retry_count > max_retries` so the check will fail as expected when the `max_retries` is exceeded and not before.
I also noticed that no error log is emitted when the job fails and the `max_retries` is exceeded, so I added a log …
> Fix off-by-one error for max retries check

- src/lib.rs
- src/redis.rs
Problem
-------
Curently, `RedisConnection::zrem` only accepts a single string as an argument. This means, in order to remove multiple items, the method needs to be called multiple times. Alternatively, one can use the underlying connection via `RedisConnection::unnamespaced_borrow_mut`, which accepts any `ToRedisArgs` type. However, then the key is not namespaced. 
Solution
--------
Allow `RedisConnection::zrem` to accept any `ToRedisArgs` like the other methods in `RedisConnection` do already.
Also updates other `RedisConnection` methods that only accept a single string value to accept `ToRedisArgs` instead.
> Allow RedisConnection methods to accept ToRedisArgs

- examples/demo.rs
- examples/namespaced_demo.rs
- examples/producer-demo.rs
- examples/unique.rs
- tests/process_async_test.rs
- tests/process_scheduled_job_test.rs
- tests/process_unique_job_test.rs
- tests/server_middleware_test.rs
`mut` was removed from `Worker#perform*` methods in [PR 28](https://github.com/film42/sidekiq-rs/pull/28). However, it was not removed from some of the examples. This PR removes the now unnecessary `mut`s.
> Remove unnecessary `mut` from examples

- src/lib.rs
- src/processor.rs
Problem
-------
If an app's workload is largely IO bound (querying a DB, making web requests and waiting for responses, etc), its workers will spend a large percentage of time idle `await`ing for futures to complete. This in turn means the will CPU sit idle a large percentage of the time (if nothing else is running on the host), resulting in under-utilizing available CPU resources.
Solution
--------
Allow apps to configure the number of tokio tasks that are spawned for workers. This will allow the app to configure the processor to use CPU resources more efficiently. For backwards compatiblity and in order to provide a sane/safe default, the default number of workers if not provided is the host's CPU count.
> Allow configuring the number of tasks spawned for workers

- src/processor.rs
Problem
-------
When there are no sidekiq jobs available in redis, there are no `await`s between when `brpop`returns and when the next connection is acquired from the pool. This means tokio's task scheduler doesn't have a chance to switch to another task that's waiting for a connection.
Solution
--------
Add a `tokio::task::yield_now().await` in the case where there is no actual job to handle. This allows tokio's task scheduler to wake up a different task that's waiting for a connection.
https://github.com/film42/sidekiq-rs/issues/43
> Add a yield to prevent `Processor` from hogging redis connections

- README.md
The `sidekiq::Processor` was recently updated to allow configuring the number of worker tasks it spawns. Add a section for this to the readme.
Also, add a "Best practices" section, and add the recommendation to use a separate connection pool for enqueuing vs fetching from Redis as discussed in https://github.com/film42/sidekiq-rs/issues/43.
> Update readme with details re: num_workers config and separate push/fetch pools

- src/processor.rs
With a `Vec`, the handles are awaited in the order they are inserted. This means that if a tasks exits with an error, it won't be logged until the tasks ahead of it in the `Vec` complete, which is typically not until the entire application exits.
Tokio provides an alternative structure to track tasks -- a `JoinSet`. When iterating over a `JoinSet`, task results are returned in the order that the tasks are completed instead of the order they're spawned. This could potentially be used to optionally shutdown the entire processor if any of its tasks exit with an error (this would be a new config).
> Use a `JoinSet` to manage the processor's tasks instead of a `Vec`

- src/lib.rs
- src/middleware.rs
- src/periodic.rs
- src/stats.rs
According to the sidekiq docs, `sidekiq_options` `retry` param can be either boolean or a number.
Change the param of the retry argument to be a JsonValue for now, as it's a convenient wrapper over different basic types
> Fix type of retry option: `retry` can be boolean or a number

- src/periodic.rs
- src/redis.rs
- src/scheduled.rs
- src/stats.rs
It was reported in https://github.com/film42/sidekiq-rs/pull/50 that we have a race-condition with this scheduled enqueuer code. I think the issue was that I was _assuming_ that redis would coerce a 0 to false and a 1 to true, but  I don't think that's really the case. (Still need to double check that).
Better yet, we should add a new test to prove this.
NOTE: I also updated the `n` reported by this method to only count the `n` if it actually enqueued a job.
NOTE 2: I think it's best if we bring the enqueue batch size down from 100 to 10.
> Only enqueue a sched job if the worker removed it

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/processor.rs
- tests/server_middleware_test.rs
As usual, caught a few things writing tests. Tests are awesome.
> Add tests around new RetryOpts features

- src/processor.rs
- src/stats.rs
Thanks to @Antti for finding this bug and reporting it via https://github.com/film42/sidekiq-rs/pull/50
> Have stats use num_workers as concurrency metric, not cpu cores

- src/lib.rs
- src/middleware.rs
- src/periodic.rs
- tests/server_middleware_test.rs
This also adds the error_class field that was missing.
> Add support for a retry_queue + tests

- src/lib.rs
- src/processor.rs
- tests/process_async_test.rs
The Redis API used to fetch jobs
([brpop](https://redis.io/docs/latest/commands/brpop/)) checks queues for jobs in the order the queues are provided. This means that if the first queue in the list provided to `Processor::new` always has an item, the other queues will never have their jobs run.
Add a `BalanceStrategy` to allow ensuring that no queue is starved indefinitely. The initial (and default) algorithm implemented is a basic round robin algorithm. Before each fetch from Redis, the `Processor#queues` list is rotated by 1, ensuring that every queue has a chance to have its jobs run.
> feat: Add queue fetch balance strategy

- Cargo.lock
- Cargo.toml
- src/redis.rs
FYI updating bb8 is a breaking change since its types are used in the public api of `sidekiq-rs`. The other dependency updates shouldn't be breaking changes as far as I can tell.
> chore!: Update bb8 and other dependencies
